Update Culture Languages and the LanguageSelectDialog
Pjb518/FoundryVTT-Level-Up-Official pull request #26
Opened 2023-02-01 04:21 UTC by KageJittai

* LanguageSelectDialog is now extended from TraitSelectDialog, removing the need for a custom svelte pages.
  * Culture item format adjusted to take advantage of actor handlers.
  * Removed localizeLanguage and isCustomLanguage helpers, no longer required with prepareLanguageProficiencies handler.
  * Actor Sheet now uses a static method of the LanguageSelectDialog to retrieve user's language selections.

2023-02-02 17:29 UTC, NekroDarkmoon requested changes

2023-02-02 17:29 UTC, NekroDarkmoon commented on src/apps/dialogs/initializers/LanguageSelectDialog.js
> +  static async createRecommendLanguages(titleName, known, recommended, additional = 0) {
Wondering if we can come up with a better name for the function. It's a bit hard to guess what this does when calling it from outside the file.

2023-02-02 17:29 UTC, NekroDarkmoon commented on src/apps/components/pages/CultureDetailsTab.svelte
> +    function handleAddFeature(event) {
If we expect to use these handlers in other item types are well, we could probably turn these into separate files and import them

2023-02-02 17:29 UTC, NekroDarkmoon commented on src/apps/components/pages/CultureDetailsTab.svelte
> +    async function openLanguage() {
This could possibly be `openLanguageSelectDialog`

2023-02-02 17:29 UTC, NekroDarkmoon commented on src/apps/components/pages/CultureDetailsTab.svelte
> +            $item.update({ "system.proficiencies.languages": newLanguages });
Can use the`updateDataFromField` helper here

2023-02-02 17:29 UTC, NekroDarkmoon commented on public/template.json
> +        "additional_languages": 0
Should use camel case instead of snake case

2023-02-06 14:44 UTC, merged

2023-02-06 14:45 UTC, Pjb518 commented
I've made the requested changes to this PR and merged it into `development`.