Implements base work needed for theming
Pjb518/FoundryVTT-Level-Up-Official pull request #440
Opened 2024-07-09 14:22 UTC by julaberry

Standardization of the following css variables:

2024-07-10 00:39 UTC, NekroDarkmoon commented on src/apps/chat/body/CardBody.svelte
Note: This needs to be tested to see if it actually works.

2024-07-10 00:42 UTC, NekroDarkmoon commented on src/apps/chat/body/PromptButton.svelte
> +            color: var(--hover-color, var(--a5e-color-text-dark));
This doesn't work. `color: var(--hover-color, --a5e-color-text-dark)`

2024-07-10 00:49 UTC, NekroDarkmoon commented on src/apps/components/ItemInnerWrapper.svelte
> +        color: var(--icon-color-active, var(--a5e-color-primary));
Same as before. Doesn't need a nested var.

2024-07-10 00:49 UTC, NekroDarkmoon commented on src/apps/components/ItemInnerWrapper.svelte
> +            color: var(--icon-color-active, var(--a5e-color-primary));
Same as before. Doesn't need a nested var.

2024-07-10 00:59 UTC, NekroDarkmoon commented on src/apps/components/actorSidebar/RestButton.svelte
>              }
Note: Need to test if this works.

2024-07-10 01:00 UTC, NekroDarkmoon commented on src/apps/components/actorUtilityBar/CreateMenu.svelte
>          --tjs-icon-button-diameter="1.1rem"
Note: Need to test if this works.

2024-07-10 01:02 UTC, NekroDarkmoon commented on src/apps/components/effectChanges/ChangeConfiguration.svelte
> +        --font-size="var(--a5e-text-size-sm)"
Need to test if these work.

2024-07-10 01:11 UTC, NekroDarkmoon commented on src/apps/components/pages/EffectsEffectTab.svelte
> +        --tjs-icon-button-transition="var(--a5e-transition-standard)-standard)"
this seems to have fucked up.

2024-07-10 01:33 UTC, NekroDarkmoon requested changes
Some things need to be fixed while others need validation

2024-07-12 04:22 UTC, julaberry commented on src/apps/components/pages/EffectsEffectTab.svelte
> +        --tjs-icon-button-transition="var(--a5e-transition-standard)-standard)"
Fixed

2024-07-12 07:54 UTC, NekroDarkmoon approved these changes

2024-07-12 07:55 UTC, merged